name: Code analysis of server code
on:
  push:
    branches:
      - main
    paths: # Only applicable if any go code was changed
      - 'server/**/*.go'
      - 'server/*.go'
jobs:
  Analyze-Server:
    runs-on: ubuntu-latest
    if: github.repository == 'ansible/aoc-azure-aap-installer'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2' # The Go version to download (if necessary) and use. Make sure it is in sync with build and test workflow
      - name: Run server tests
        run: |
          cd server
          make test-with-coverage
      - name: Run SonarQube analysis
        env:
          SONAR_PROJECT_TOKEN: ${{ secrets.SONAR_PROJECT_TOKEN }}
        run: tools/run_sonarqube.sh server
